 CREATE PROC insertAttendee	
  AS
  BEGIN
    BEGIN TRY
	INSERT INTO Attendee VALUES	( 'Long'	,'Amanda',	 '10 Napa Ct.', 'Lebanon', '97355'	,	 'ALong@gmail.com',	8	);
	INSERT INTO Attendee VALUES	( 'Shan'	,'Christian',	 '1000 Bidweld Street', 'Haney', 'V2W 1W2'	,	 'CShan@gmail.com',	2	);
	INSERT INTO Attendee VALUES	( 'Sara'	,'Troy',	 '1002 N. Spoonwood Court', 'Hervey Bay', '4655'	,	 'TSara@gmail.com',	9	);
	INSERT INTO Attendee VALUES	( 'Baker'	,'Kaitlyn',	 '1003 Matterhorn Ct', 'Lebanon', '97355'	,	 'KBaker@gmail.com',	8	);
	INSERT INTO Attendee VALUES	( 'Ma'	,'Suzanne',	 '1005 Matterhorn Ct.', 'Cambridge', 'CB4 4BZ'	,	 'SMa@gmail.com',	4	);
	INSERT INTO Attendee VALUES	( 'Jones'	,'Anna',	 '1005 Matterhorn Ct.', 'Mill Valley', '94941'	,	 'AJones@gmail.com',	3	);
	INSERT INTO Attendee VALUES	( 'Baker'	,'Carlos',	 '1005 Tanager Court', 'Corvallis', '97330'	,	 'CBaker@gmail.com',	8	);
	INSERT INTO Attendee VALUES	( 'Munoz'	,'Tanya',	 '1005 Tanager Court', 'Milsons Point', '2061'	,	 'TMunoz@gmail.com',	6	);
	INSERT INTO Attendee VALUES	( 'Gill'	,'Tabitha',	 '1006 Deercreek Ln', 'Bellflower', '90706'	,	 'TGill@gmail.com',	3	);
	INSERT INTO Attendee VALUES	( 'Lee'	,'Alexis',	 '1006 Deercreek Ln', 'Torrance', '90505'	,	 'ALee@gmail.com',	3	);
	INSERT INTO Attendee VALUES	( 'Suri'	,'Erick',	 '101 Adobe Dr', 'Coffs Harbour', '2450'	,	 'ESuri@gmail.com',	6	);
	INSERT INTO Attendee VALUES	( 'Evans'	,'Marcus',	 '101 Adobe Dr', 'Puyallup', '98371'	,	 'MEvans@gmail.com',	11	);
	INSERT INTO Attendee VALUES	( 'Clark'	,'Marcus',	'101 Avenue de la Gare', 'Peterborough', 'PB12'	,	 'MClark@gmail.com',	4	);
	INSERT INTO Attendee VALUES	( 'Xu'	,'Gilbert',	 '1010 Maple', 'Baltimore', '21201'	,	 'GXu@gmail.com',	5	);
	INSERT INTO Attendee VALUES	( 'Rubio'	,'Paula',	 '1011 Yolanda Circle', 'Berkeley', '94704'	,	 'PRubio@gmail.com',	3	);
	INSERT INTO Attendee VALUES	( 'Isla'	,'Julian',	 '1011 Yolanda Circle', 'N. Vancouver', 'V7L 4J4'	,	 'JIsla@gmail.com',	2	);
	INSERT INTO Attendee VALUES	( 'Scott'	,'Jesse',	 '1013 Holiday Hills Dr.', 'Bremerton', '98312'	,	 'JScott@gmail.com',	11	);
	INSERT INTO Attendee VALUES	( 'Sanz'	,'Naomi',	 '1013 Holiday Hills Dr.', 'Gateshead', 'GA10'	,	 'NSanz@gmail.com',	4	);
	INSERT INTO Attendee VALUES	( 'Lee'	,'Isabella',	 '1015 Lynwood Drive', 'Metchosin', 'V9'	,	 'ILee@gmail.com',	2	);
	INSERT INTO Attendee VALUES	( 'Yuan'	,'Dawn',	 '1019 Carletto Drive', 'Berkeley', '94704'	,	 'DYuan@gmail.com',	3	);
	INSERT INTO Attendee VALUES	( 'Blue'	,'Olivia',	 '1019 Mt. Davidson Court', 'Burien', '98168'	,	 'OBlue@gmail.com',	11	);
	INSERT INTO Attendee VALUES	( 'Lopez'	,'Emmanuel',	 '1019 Mt. Davidson Court', 'London', 'SW8 4BG'	,	 'ELopez@gmail.com',	4	);
	INSERT INTO Attendee VALUES	( 'Yang'	,'Nathan',	 '102 Vista Place', 'Santa Monica', '90401'	,	 'NYang@gmail.com',	3	);
	INSERT INTO Attendee VALUES	( 'Wood'	,'Gabrielle',	 '1020 Book Road', 'Bremerton', '98312'	,	 'GWood@gmail.com',	11	);
	INSERT INTO Attendee VALUES	( 'Anand'	,'Katrina',	 '1020 Carletto Drive', 'Matraville', '2036'	,	 'KAnand@gmail.com',	6	);
	INSERT INTO Attendee VALUES	( 'Jones'	,'Anthony',	 '1020 Carletto Drive', 'Santa Cruz', '95062'	,	 'AJones@gmail.com',	3	);
	INSERT INTO Attendee VALUES	( 'Reed'	,'Natalie',	 '1023 Hawkins Street', 'Lebanon', '97355'	,	 'NReed@gmail.com',	8	);
	INSERT INTO Attendee VALUES	( 'Ross'	,'Dakota',	 '1024 Walnut Blvd.', 'Colma', '94014'	,	 'DRoss@gmail.com',	3	);
	INSERT INTO Attendee VALUES	( 'Goel'	,'Shawn',	 '1025 Holly Oak Drive', 'Leeds', 'LE18'	,	 'SGoel@gmail.com',	4	);
	INSERT INTO Attendee VALUES	( 'Diaz'	,'Nicole',	 '1025 R St.', 'Kirkland', '98033'	,	 'NDiaz@gmail.com',	11	);
	INSERT INTO Attendee VALUES	( 'Davis'	,'Wyatt',	 '1025 Yosemite Dr.', 'OR City', '97045'	,	 'WDavis@gmail.com',	8	);
	INSERT INTO Attendee VALUES	( 'Huang'	,'Christy',	 '1028 Green View Court', 'Chula Vista', '91910'	,	 'CHuang@gmail.com',	3	);
	INSERT INTO Attendee VALUES	( 'Evans'	,'Sydney',	 '1028 Green View Court', 'OR City', '97045'	,	 'SEvans@gmail.com',	8	);
	INSERT INTO Attendee VALUES	( 'Baker'	,'Katherine',	 '1037 Hayes Court', 'Stoke-on-Trent', 'AS23'	,	 'KBaker@gmail.com',	4	);
	INSERT INTO Attendee VALUES	( 'Wood'	,'Edward',	 '1039 Adelaide St.', 'West Covina', '91791'	,	 'EWood@gmail.com',	3	);
	INSERT INTO Attendee VALUES	( 'Rai'	,'J7nny',	 '104 Hilltop Dr.', 'Springwood', '2777'	,	 'JRai@gmail.com',	6	);
	INSERT INTO Attendee VALUES	( 'Moore'	,'Emily',	 '104 Kaski Ln.', 'Portland', '97205'	,	 'EMoore@gmail.com',	8	);
	INSERT INTO Attendee VALUES	( 'Yang'	,'Randy',	 '1040 Greenbush Drive', 'Silverwater', '2264'	,	 'RYang@gmail.com',	6	);
	INSERT INTO Attendee VALUES	( 'Ruiz'	,'Roy',	 '1040 Northridge Road', 'London', 'W1X3SE'	,	 'RRuiz@gmail.com',	4	);
	INSERT INTO Attendee VALUES	( 'Sun'	,'Marshall',	 '1044 San Carlos', 'Cincinnati', '45202'	,	 'MSun@gmail.com',	7	);
	INSERT INTO Attendee VALUES	( 'Perez'	,'Gabriella',	 '1045 Lolita Drive', 'Torrance', '90505'	,	 'GPerez@gmail.com',	3	);
	INSERT INTO Attendee VALUES	( 'Gill'	,'Erika',	 '1045 Lolita Drive', 'Townsville', '4810'	,	 'EGill@gmail.com',	9	);
	INSERT INTO Attendee VALUES	( 'Shen'	,'Kathryn',	 '1047 Las Quebradas Lane', 'North Sydney', '2055'	,	 'KShen@gmail.com',	6	);
	INSERT INTO Attendee VALUES	( 'Yuan'	,'Sharon',	 '1048 Burwood Way', 'Hervey Bay', '4655'	,	 'SYuan@gmail.com',	9	);
	INSERT INTO Attendee VALUES	( 'Lee'	,'10toria',	 '1048 Las Quebradas Lane', 'Walla Walla', '99362'	,	 'VLee@gmail.com',	11	);
	INSERT INTO Attendee VALUES	( 'Arun'	,'Brenda',	 '1048 Las Quebradas Lane', 'Wollongong', '2500'	,	 'BArun@gmail.com',	6	);
	INSERT INTO Attendee VALUES	( 'Scott'	,'Alex',	 '105 Clark Creek Lane', 'Port Macquarie', '2444'	,	 'AScott@gmail.com',	6	);
	INSERT INTO Attendee VALUES	( 'Luo'	,'Yolanda',	 '105 Woodruff Ln.', 'Bellingham', '98225'	,	 'YLuo@gmail.com',	11	);
	INSERT INTO Attendee VALUES	( 'Vance'	,'Martin',	 '1050 Creed Ave', 'London', 'W10 6BL'	,	 'MVance@gmail.com',	4	);
	INSERT INTO Attendee VALUES	( 'Roberts'	,'Jeremy',	 '081 boulevard du Montparnasse', 'Seattle', '98104'	,	 'JRoberts@yahoo.com',	11	);
	INSERT INTO Attendee VALUES	( 'Ramirez'	,'Amanda',	 '1 Smiling Tree Court', 'Los Angeles', '90012'	,	 'ARamirez@yahoo.com',	3	);
	INSERT INTO Attendee VALUES	( 'Nelson'	,'Jada',	 '100 rue des Rosiers', 'Everett', '98201'	,	 'JNelson@yahoo.com',	11	);
	INSERT INTO Attendee VALUES	( 'Wright'	,'Hunter',	 '1002 N. Spoonwood Court', 'Berkeley', '94704'	,	 'HWright@yahoo.com',	3	);
	INSERT INTO Attendee VALUES	( 'Wright'	,'Sierra',	 '1005 Fremont Street', 'Colma', '94014'	,	 'SWright@yahoo.com',	3	);
	INSERT INTO Attendee VALUES	( 'Simmons'	,'Sarah',	 '1005 Valley Oak Plaza', 'Langley', 'V3A 4R2'	,	 'SSimmons@yahoo.com',	2	);
	INSERT INTO Attendee VALUES	( 'Samant'	,'Mandar',	 '1005 Valley Oak Plaza', 'London', 'SW6 SBY'	,	 'MSamant@yahoo.com',	4	);
	INSERT INTO Attendee VALUES	( 'Rogers'	,'Isaiah',	 '1007 Cardinet Dr.', 'El Cajon', '92020'	,	 'IRogers@yahoo.com',	3	);
	INSERT INTO Attendee VALUES	( 'Foster'	,'Ian',	 '1008 Lydia Lane', 'Burbank', '91502'	,	 'IFoster@yahoo.com',	3	);
	INSERT INTO Attendee VALUES	( 'Miller'	,'Ben',	 '101 Candy Rd.', 'Redmond', '98052'	,	 'BMiller@yahoo.com',	11	);
	INSERT INTO Attendee VALUES	( 'Barnes'	,'Sarah',	 '1011 Green St.', 'Bellingham', '98225'	,	 'SBarnes@yahoo.com',	11	);
	INSERT INTO Attendee VALUES	( 'Martin'	,'Casey',	 '1013 Buchanan Rd', 'Port Macquarie', '2444'	,	 'CMartin@yahoo.com',	6	);
	INSERT INTO Attendee VALUES	( 'Murphy'	,'10toria',	 '1013 Buchanan Rd', 'Yakima', '98901'	,	 'VMurphy@yahoo.com',	11	);
	INSERT INTO Attendee VALUES	( 'Rogers'	,'Sydney',	 '1016 Park Avenue', 'Burbank', '91502'	,	 'SRogers@yahoo.com',	3	);
	INSERT INTO Attendee VALUES	( 'Hernandez'	,'Marvin',	 '1019 Book Road', 'Rhodes', '2138'	,	 'MHernandez@yahoo.com',	6	);
	INSERT INTO Attendee VALUES	( 'Carter'	,'Carlos',	 '1019 Buchanan Road', 'Woodland Hills', '91364'	,	 'CCarter@yahoo.com',	3	);
	INSERT INTO Attendee VALUES	( 'Garcia'	,'Rebekah',	 '1019 Candy Rd.', 'Coffs Harbour', '2450'	,	 'RGarcia@yahoo.com',	6	);
	INSERT INTO Attendee VALUES	( 'Henderson'	,'Haley',	 '1019 Chance Drive', 'Sedro Woolley', '98284'	,	 'HHenderson@yahoo.com',	11	);
	INSERT INTO Attendee VALUES	( 'Taylor'	,'Jacob',	 '1019 Kenwal Rd.', 'Lake Oswego', '97034'	,	 'JTaylor@yahoo.com',	8	);
	INSERT INTO Attendee VALUES	( 'Martin'	,'Seth',	 '1019 Pennsylvania Blvd', 'Marysville', '98270'	,	 'SMartin@yahoo.com',	11	);
	INSERT INTO Attendee VALUES	( 'Suarez'	,'Larry',	 '102 Vista Place', 'Milton Keynes', 'MK8 8DF'	,	 'LSuarez@yahoo.com',	4	);
	INSERT INTO Attendee VALUES	( 'Vargas'	,'Garrett',	 '10203 Acorn Avenue', 'Calgary', 'T2P 2G8'	,	 'GVargas@yahoo.com',	4	);
	INSERT INTO Attendee VALUES	( 'Martinez'	,'Abby',	 '1023 Hawkins Street', 'Townsville', '4810'	,	 'AMartinez@yahoo.com',	9	);
	INSERT INTO Attendee VALUES	( 'Thomas'	,'Justin',	 '1023 Riveria Way', 'Burbank', '91502'	,	 'JThomas@yahoo.com',	3	);
	INSERT INTO Attendee VALUES	( 'Martinez'	,'Evelyn',	 '1023 Riviera Way', 'Oxford', 'OX1'	,	 'EMartinez@yahoo.com',	4	);
	INSERT INTO Attendee VALUES	( 'Chapman'	,'Pamela',	 '1025 Yosemite Dr.', 'Townsville', '4810'	,	 'PChapman@yahoo.com',	9	);
	INSERT INTO Attendee VALUES	( 'Griffin'	,'Kayla',	 '1026 Mt. Wilson Pl.', 'Lynnwood', '98036'	,	 'KGriffin@yahoo.com',	11	);
	INSERT INTO Attendee VALUES	( 'Navarro'	,'Jill',	 '1026 Mt. Wilson Pl.', 'South Melbourne', '3205'	,	 'JNavarro@yahoo.com',	10	);
	INSERT INTO Attendee VALUES	( 'Walker'	,'Nathan',	 '1028 Indigo Ct.', 'Issaquah', '98027'	,	 'NWalker@yahoo.com',	11	);
	INSERT INTO Attendee VALUES	( 'Moreno'	,'Tabitha',	 '1028 Indigo Ct.', 'Warrnambool', '3280'	,	 'TMoreno@yahoo.com',	10	);
	INSERT INTO Attendee VALUES	( 'Sanchez'	,'Mason',	 '1028 Royal Oak Rd.', 'Burlingame', '94010'	,	 'MSanchez@yahoo.com',	3	);
	INSERT INTO Attendee VALUES	( 'Navarro'	,'Natasha',	 '1029 Birchwood Dr', 'Burien', '98168'	,	 'NNavarro@yahoo.com',	11	);
	INSERT INTO Attendee VALUES	( 'Russell'	,'Kevin',	 '1029 Birchwood Dr', 'Olympia', '98501'	,	 'KRussell@yahoo.com',	11	);
	INSERT INTO Attendee VALUES	( 'Rivera'	,'Katelyn',	 '1030 Ambush Dr.', 'Bury', 'PE17'	,	 'KRivera@yahoo.com',	4	);
	INSERT INTO Attendee VALUES	( 'Ortega'	,'Alfredo',	 '1032 Buena Vista', 'North Ryde', '2113'	,	 'AOrtega@yahoo.com',	6	);
	INSERT INTO Attendee VALUES	( 'Campbell'	,'Andrea',	 '1032 Coats Road', 'Stoke-on-Trent', 'AS23'	,	 'ACampbell@yahoo.com',	4	);
	INSERT INTO Attendee VALUES	( 'Peterson'	,'Jeremy',	 '1035 Arguello Blvd.', 'San Diego', '92102'	,	 'JPeterson@yahoo.com',	3	);
	INSERT INTO Attendee VALUES	( 'Ramirez'	,'Arianna',	 '1036 Mason Dr', 'Port Orchard', '98366'	,	 'ARamirez@yahoo.com',	11	);
	INSERT INTO Attendee VALUES	( 'Sharma'	,'Mario',	 '1039 Adelaide St.', 'Port Macquarie', '2444'	,	 'MSharma@yahoo.com',	6	);
	INSERT INTO Attendee VALUES	( 'Collins'	,'Adam',	 '104 Hilltop Dr.', 'Concord', '94519'	,	 'ACollins@yahoo.com',	3	);
	INSERT INTO Attendee VALUES	( 'Martin'	,'Taylor',	 '1040 Greenbush Drive', 'Newton', 'V2L3W8'	,	 'TMartin@yahoo.com',	2	);
	INSERT INTO Attendee VALUES	( 'Collins'	,'Gabriel',	 '1040 Northridge Road', 'Woodland Hills', '91364'	,	 'GCollins@yahoo.com',	3	);
	INSERT INTO Attendee VALUES	( 'Martin'	,'Randall',	 '1042 Hooftrail Way', 'Newcastle', '2300'	,	 'RMartin@yahoo.com',	6	);
	INSERT INTO Attendee VALUES	( 'Jenkins'	,'Samantha',	 '1046 Cloverleaf Circle', 'Shawnee', 'V8Z 4N5'	,	 'SJenkins@yahoo.com',	2	);
	INSERT INTO Attendee VALUES	( 'Simmons'	,'Justin',	 '1046 San Carlos Avenue', 'Colma', '94014'	,	 'JSimmons@yahoo.com',	3	);
	INSERT INTO Attendee VALUES	( 'Winston'	,'Ethan',	 '1047 Las Quebradas Lane', 'Oak Bay', 'V8P'	,	 'EWinston@yahoo.com',	2	);
	INSERT INTO Attendee VALUES	( 'Roberts'	,'Hunter',	 '1048 Burwood Way', 'Haney', 'V2W 1W2'	,	 'HRoberts@yahoo.com',	2	);
	INSERT INTO Attendee VALUES	( 'Murphy'	,'Nathaniel',	 '105 Woodruff Ln.', 'Oakland', '94611'	,	 'NMurphy@yahoo.com',	3	);
	INSERT INTO Attendee VALUES	( 'Wilson'	,'Charles',	 '1050 Creed Ave', 'Lebanon', '97355'	,	 'CWilson@yahoo.com',	8	);
	INSERT INTO Attendee VALUES	( 'Alvarez'	,'Carrie',	 '1050 Greenhills Circle', 'Lane Cove', '1597'	,	 'CAlvarez@yahoo.com',	6	);
	INSERT INTO Attendee VALUES	( 'Alexander'	,'Paige',	 '1050 Greenhills Circle', 'Langley', 'V3A 4R2'	,	 'PAlexander@yahoo.com',	2	);
 INSERT INTO Attendee VALUES (	'Kevin'	,'Goff',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'John'	,'Sterrett',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Sunil'	,'Kadimdiwan',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'James'	,'Serra',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Stacia'	,'Misner',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'SQLSatruday'	,'364',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Steve'	,'Simon',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Robert'	,'Pearl',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Jason'	,'Horner',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Paul'	,'Rizza',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'John'	,'Miner',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Andy'	,'Leonard',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'George'	,'Walters',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Allan'	,'Hirt',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Kevin'	,'Goff',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Jack'	,'Corbett',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Kevin'	,'Schenega',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Chris'	,'Bell',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Kennie'	,'Pontoppidan',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Carl'	,'Berglund',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Dennis'	,'Messina',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Richie'	,'Rump',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Chris'	,'Bell',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Jack'	,'Corbett',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Aaron'	,'Bertrand',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Greg'	,'Moore',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Aaron'	,'Bertrand',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Kevin'	,'Goff',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Grant'	,'Fritchey',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Jason'	,'Brimhall',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Brent'	,'Ozar',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'David'	,'Bermingham',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'James'	,'Serra',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'James'	,'Serra',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Kevin'	,'Goff',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Paresh'	,'Motiwala',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Kevin'	,'Goff',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Mike'	,'Walsh',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Thomas'	,'Grohser',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Joe'	,'Chang',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'John'	,'Miner',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Paresh'	,'Motiwala',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Mickey'	,'Stuewe',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Allan'	,'Hirt',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Allan'	,'Hirt',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Robert'	,'Pearl',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Steve'	,'Simon',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Steve'	,'Simon',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Gigi'	,'Bell',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'John'	,'Flannery',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Allan'	,'Hirt',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Jason'	,'Horner',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Edward'	,'Pollack',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Jeremiah'	,'Peschka',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Jeremiah'	,'Peschka',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Steve'	,'Simon',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Steve'	,'Simon',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Michael'	,'Wharton',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Jason'	,'Horner',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Chris'	,'Bell',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Edward'	,'Pollack',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Steve'	,'Simon',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Mike'	,'Hillwig',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Stacia'	,'Misner',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Hilary'	,'Cotter',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Jason'	,'Brimhall',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Hilary'	,'Cotter',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Hilary'	,'Cotter',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Stéphane'	,'Fréchette',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Paul'	,'Rizza',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Allan'	,'Hirt',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Kennie'	,'Pontoppidan',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Kevin'	,'Goff',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'George'	,'Walters',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Steve'	,'Simon',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'George'	,'Walters',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'George'	,'Walters',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'David'	,'Peter',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Jason'	,'Brimhall',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Steve'	,'Simon',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Steve'	,'Simon',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Kevin'	,'Goff',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Thomas'	,'Grohser',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Brandon'	,'Leach',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Andy'	,'Leonard',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Hilary'	,'Cotter',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'John'	,'Miner',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Melissa'	,'Riley',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Adam'	,'Jorgensen',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Steve'	,'Simon',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Chris'	,'Seferlis',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Mohammad'	,'Yusuf',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Kennie'	,'Pontoppidan',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Thomas'	,'Grohser',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Joe'	,'Chang',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Michael'	,'Wharton',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Mike'	,'Walsh',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'John'	,'Miner',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Mickey'	,'Stuewe',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'John'	,'Miner',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'James'	,'Serra',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'James'	,'Serra',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'David'	,'Peter',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Steve'	,'Simon',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Steve Hansen'	,'Simon',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Kevin'	,'Goff',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Steve'	,'Simon',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'John'	,'Flannery',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'John'	,'Flannery',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Steve'	,'Simon',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Edward'	,'Pollack',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Mohammad'	,'Yusuf',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Michael'	,'Corey',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Edward'	,'Pollack',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES (	'Brent'	,'Ozar',	'na','na','xxxxx-xx '		,'na',	3	);
 INSERT INTO Attendee VALUES ('James'	,'Serra', 'na',	'na','xxxxx-xx '	,'na',	3	);


	END TRY
    BEGIN CATCH
    END CATCH
  END

EXEC insertAttendee
GO

select * from Attendee ORDER BY attendeelast, attendeeFirst ASC;
