  CREATE PROC insertPresenterPresentation
  AS
  BEGIN
    BEGIN TRY
	INSERT INTO  PresenterPresentation VALUES	('	A dive into Data Quality Services',	'Steve Simon',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	A Dynamic World Demands Dynamic SQL',	'Jeremiah Peschka',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	A Dynamic World Demands Dynamic SQL',	'Jeremiah Peschka',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	Absolute Introductory Session on SQL Server 2014 In-Memory Optimized Databases (Hekaton)',	'Kevin Goff',1,626);
	INSERT INTO  PresenterPresentation VALUES	('	AlwaysOn: Improve reliability and reporting performance with one cool tech',	'Chris Seferlis',1,588);
	INSERT INTO  PresenterPresentation VALUES	('	An introduction to Data Mining',	'Steve Simon',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	An Introduction to Database Design',	'Mohammad Yusuf',1,588);
	INSERT INTO  PresenterPresentation VALUES	('	Autogenerating a process data warehouse',	'Kennie Pontoppidan',3,588);
	INSERT INTO  PresenterPresentation VALUES	('	Automate your daily checklist with PBM and CMS',	'John Sterrett',2,626);
	INSERT INTO  PresenterPresentation VALUES	('	Automated Installing and Configuration of SQL2014/SQL2012 AlwaysOn Across Multiple Datacenters',	'Thomas Grohser',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Automated Installing and Configuration of SQL2014/SQL2012 AlwaysOn Across Multiple Datacenters',	'Thomas Grohser',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	Automating Execution Plan Analysis',	'Joe Chang',3,616);
	INSERT INTO  PresenterPresentation VALUES	('	Automating Execution Plan Analysis',	'Joe Chang',3,588);
	INSERT INTO  PresenterPresentation VALUES	('	Automating SQL Server using PowerShell',	'Michael Wharton',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Balanced Scorecards using SSRS',	'Sunil Kadimdiwan',2,626);
	INSERT INTO  PresenterPresentation VALUES	('	Baselines and Performance Monitoring with PAL',	'Mike Walsh',1,588);
	INSERT INTO  PresenterPresentation VALUES	('	Basic Database Design',	'John Miner',1,588);
	INSERT INTO  PresenterPresentation VALUES	('	Basic Database Programming',	'John Miner',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	Become a BI Independent Consultant!',	'James Serra',1,626);
	INSERT INTO  PresenterPresentation VALUES	('	Becoming a Top DBA--Learning Automation in SQL Server',	'Joseph D Antoni',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	Best Practices Document',	'Paresh Motiwala',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	Best Practices for Efficient SSRS Report Creation',	'Mickey Stuewe',1,588);
	INSERT INTO  PresenterPresentation VALUES	('	Biggest Loser: Database Edition',	'John Miner',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Building a BI Solution in the Cloud',	'Stacia Misner',2,626);
	INSERT INTO  PresenterPresentation VALUES	('	Building an Effective Data Warehouse Architecture',	'James Serra',1,588);
	INSERT INTO  PresenterPresentation VALUES	('	Building an Effective Data Warehouse Architecture with the cloud and MPP',	'James Serra',1,588);
	INSERT INTO  PresenterPresentation VALUES	('	Bulk load and minimal logged inserts',	'David Peter Hansen',3,588);
	INSERT INTO  PresenterPresentation VALUES	('	Business Analytics with SQL Server & Power Map:Everything you want to know but were afraid to ask',	'Steve Simon',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Challenges to designing financial warehouses, lessons learnt',	'Steve Simon',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Change Data Capture in SQL Server 2008/2012',	'Kevin Goff',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Changing Your Habits to Improve the Performance of Your T-SQL',	'Mickey Stuewe',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	Clusters Your Way: #SANLess Clusters for Physical, Virtual, and Cloud Environments',	'Allan Hirt and SIOS Technology',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	Clusters Your Way: #SANLess Clusters for Physical, Virtual, and Cloud Environments',	'Allan Hirt',3,616);
	INSERT INTO  PresenterPresentation VALUES	('	Coffee Break',	'SQLSatruday 364',3,626);
	INSERT INTO  PresenterPresentation VALUES	('	Creating A Performance Health Repository - using MDW',	'Robert Pearl',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	Creating efficient and effective SSRS BI Solutions',	'Steve Simon',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	Creating efficient and effective SSRS BI Solutions',	'Steve Simon',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Data Partitioning',	'John Flannery',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Data Tier Application Testing with NUnit and Distributed Replay',	'John Flannery',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Database design for mere developers',	'Steve Simon',2,626);
	INSERT INTO  PresenterPresentation VALUES	('	Database design for mere developers',	'Steve Simon',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Database Design: Solving Problems Before they Start!',	'Edward Pollack',1,588);
	INSERT INTO  PresenterPresentation VALUES	('	Database Modeling and Design',	'Mohammad Yusuf',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Database Virtualization and Drinking out of the Fire Hose',	'Michael Corey',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	DAX and the tabular model',	'Steve Simon',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	DBA FOR DUMMIES',	'Robert Pearl',1,626);
	INSERT INTO  PresenterPresentation VALUES	('	Dealing With Difficult People',	'Gigi Bell',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	Development Lifecycle with SQL Server Data Tools and DACFx',	'John Flannery',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	Did You Vote Today? A DBAs Guide to Cluster Quorum',	'Allan Hirt',3,616);
	INSERT INTO  PresenterPresentation VALUES	('	Dimensional Modeling Design Patterns: Beyond Basics',	'Jason Horner',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	Dimensional Modeling Design Patterns: Beyond Basics',	'Jason Horner',2,626);
	INSERT INTO  PresenterPresentation VALUES	('	Diving Into Query Execution Plans',	'Edward Pollack',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Dynamic SQL: Writing Efficient Queries on the Fly',	'Edward Pollack',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	Easy Architecture Design for HA and DR',	'Brent Ozar',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Enhancing your career: Building your personal brand',	'James Serra',1,588);
	INSERT INTO  PresenterPresentation VALUES	('	Establishing a SLA',	'Thomas Grohser',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	ETL not ELT! Common mistakes and misconceptions about SSIS',	'Paul Rizza',3,626);
	INSERT INTO  PresenterPresentation VALUES	('	Event Kickoff and Networking',	'SQLSaturday 364',3,588);
	INSERT INTO  PresenterPresentation VALUES	('	Execution Plans: What Can You Do With Them?',	'Grant Fritchey',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Faster, Better Decisions with Self Service Business Analytics',	'Sayed Saeed',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Full Text Indexing Basics',	'John Miner',1,626);
	INSERT INTO  PresenterPresentation VALUES	('	Get your Mining Model Predictions out to all',	'Steve Simon',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Getting a job with Microsoft',	'Paul Rizza',3,588);
	INSERT INTO  PresenterPresentation VALUES	('	Graph Databases for SQL Server Professionals',	'Stéphane Fréchette',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Hacking Exposé - Using SSL to Protect SQL Connections',	'Chris Bell',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Hacking the SSIS 2012 Catalog',	'Andy Leonard',1,626);
	INSERT INTO  PresenterPresentation VALUES	('	Hidden in plain sight: master your tools',	'Varsham Papikian',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Highly Available SQL Server in Windows Azure IaaS',	'David Bermingham',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	How to Make a LOT More Money as a Consultant',	'James Serra',1,588);
	INSERT INTO  PresenterPresentation VALUES	('	How to Think Like the Engine',	'Brent Ozar',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Hybrid Cloud Scenarios with SQL Server 2014',	'George Walters',2,626);
	INSERT INTO  PresenterPresentation VALUES	('	Hybrid Solutions: The Future of SQL Server Disaster Recovery',	'Allan Hirt',2,626);
	INSERT INTO  PresenterPresentation VALUES	('	Implementing Data Warehouse Patterns with the Microsoft BI Tools',	'Kevin Goff',2,626);
	INSERT INTO  PresenterPresentation VALUES	('	Inroduction to Triggers',	'Jack Corbett',1,626);
	INSERT INTO  PresenterPresentation VALUES	('	Integrating Reporting Services with SharePoint',	'Kevin Goff',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Integration Services (SSIS) for the DBA',	'David Peter Hansen',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Introducing Power BI',	'Stacia Misner',1,588);
	INSERT INTO  PresenterPresentation VALUES	('	Introduction to Database Recovery',	'John Flannery',1,588);
	INSERT INTO  PresenterPresentation VALUES	('	Introduction to High Availability with SQL Server',	'John Sterrett',1,588);
	INSERT INTO  PresenterPresentation VALUES	('	Introduction to Powershell for DBAs',	'John Sterrett',1,588);
	INSERT INTO  PresenterPresentation VALUES	('	Introduction to SQL Server - Part 1',	'Brandon Leach',1,588);
	INSERT INTO  PresenterPresentation VALUES	('	Introduction to SQL Server - Part 2',	'Brandon Leach',1,588);
	INSERT INTO  PresenterPresentation VALUES	('	Is That A Failover Cluster On Your Laptop/Desktop?',	'Allan Hirt',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Leaving the Windows Open',	'Jeremiah Peschka',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Lunch Break',	'SQLSaturday 364',3,588);
	INSERT INTO  PresenterPresentation VALUES	('	Lunchtime Keynote',	'SQLSaturday 364',3,588);
	INSERT INTO  PresenterPresentation VALUES	('	Master Data Services Best Practices',	'Steve Simon',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Master Data Services Disaster Recovery',	'Steve Simon',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Mind your language!! Cursors are a dirty word',	'Steve Simon',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Modern Data Warehousing',	'James Serra',1,588);
	INSERT INTO  PresenterPresentation VALUES	('	Monitoring Server health via Reporting Services dashboards',	'Steve Simon',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Monitoring SQL Server using Extended Events',	'Hilary Cotter',1,588);
	INSERT INTO  PresenterPresentation VALUES	('	Multidimensional vs Tabular - May the Best Model Win',	'Stacia Misner',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Murder They Wrote',	'Jason Brimhall',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Never Have to Say "Mayday!!!" Again',	'Mike Walsh',1,588);
	INSERT INTO  PresenterPresentation VALUES	('	Now you see it! Now you don’t! Conjuring many reports utilizing only one SSRS report.',	'Steve Simon',2,588);
	INSERT INTO  PresenterPresentation VALUES	('	Optimal Infrastructure Strategies for Cisco UCS, Nexus and SQL Server',	'Kevin Schenega',3,626);
	INSERT INTO  PresenterPresentation VALUES	('	Optimizing Protected Indexes',	'Chris Bell',2,626);
	INSERT INTO  PresenterPresentation VALUES	('	Partitioning as a design pattern',	'Kennie Pontoppidan',3,626);
	INSERT INTO  PresenterPresentation VALUES	('	Power BI Components in Microsoft s Self-Service BI Suite',	'Todd Chittenden',1,588);
	INSERT INTO  PresenterPresentation VALUES	('	Power to the people!!',	'Steve Simon',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	PowerShell Basics for SQLServer',	'Michael Wharton',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	PowerShell for the Reluctant DBA / Developer',	'Jason Horner',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	Prevent Recovery Amnesia – Forget the Backups',	'Chris Bell',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	Query Optimization Crash Course',	'Edward Pollack',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	Raffle',	'SQLSaturday 364',3,626);
	INSERT INTO  PresenterPresentation VALUES	('	Rapid Application Development with Master Data Services',	'Steve Simon',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	Recovery and Backup for Beginners',	'Mike Hillwig',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	Reduce, Reuse, Recycle: Automating Your BI Framework',	'Stacia Misner',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	Registrations',	'SQLSaturday 364',3,626);
	INSERT INTO  PresenterPresentation VALUES	('	Replicaton Technologies',	'Hilary Cotter',3,616);
	INSERT INTO  PresenterPresentation VALUES	('	Reporting Services for Mere DBAs',	'Jason Brimhall',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	Scaling with SQL Server Service Broker',	'Hilary Cotter',3,616);
	INSERT INTO  PresenterPresentation VALUES	('	Scaling with SQL Server Service Broker',	'Hilary Cotter',3,616);
	INSERT INTO  PresenterPresentation VALUES	('	Self-Service Data Integration with Power Query',	'Stéphane Fréchette',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	Shortcuts to Building SSIS in .Net',	'Paul Rizza',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	So You Want To Be A Consultant?',	'Allan Hirt',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	SQL anti patterns',	'Kennie Pontoppidan',3,616);
	INSERT INTO  PresenterPresentation VALUES	('	SQL Server 2012/2014 Columnstore index',	'Kevin Goff',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	SQL Server 2012/2014 Performance Tuning All Up',	'George Walters',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	SQL Server 2014 Data Access Layers',	'Steve Simon',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	SQL Server 2014 New Features',	'George Walters',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	SQL Server AlwaysOn Availability Groups',	'George Walters',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	SQL Server and the Cloud',	'David Peter Hansen',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	SQL Server Compression and what it can do for you',	'Jason Brimhall',3,616);
	INSERT INTO  PresenterPresentation VALUES	('	SQL Server Reporting Services 2014 on Steroids!!',	'Steve Simon',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	SQL Server Reporting Services Best Practices',	'Steve Simon',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	SQL Server Reporting Services, attendees choose',	'Kevin Goff',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	SQL Server Storage Engine under the hood',	'Thomas Grohser',2,616);
	INSERT INTO  PresenterPresentation VALUES	('	SQL Server Storage internals: Looking under the hood.',	'Brandon Leach',3,616);
	INSERT INTO  PresenterPresentation VALUES	('	SSIS 2014 Data Flow Tuning Tips and Tricks',	'Andy Leonard',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	Standalone to High-Availability Clusters over Lunch—with Time to Spare',	'Carl Berglund',2,626);
	INSERT INTO  PresenterPresentation VALUES	('	Stress testing SQL Server',	'Hilary Cotter',3,616);
	INSERT INTO  PresenterPresentation VALUES	('	Table partitioning for Azure SQL Databases',	'John Miner',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	Testing',	'Melissa Riley',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	The future of the data professional',	'Adam Jorgensen',1,616);
	INSERT INTO  PresenterPresentation VALUES	('	The Quest for the Golden Record:MDM Best Practices',	'Dennis Messina',1,626);
	INSERT INTO  PresenterPresentation VALUES	('	The Quest to Find Bad Data With Data Profiling',	'Richie Rump',2,626);
	INSERT INTO  PresenterPresentation VALUES	('	The Spy Who Loathed Me - An Intro to SQL Security',	'Chris Bell',1,626);
	INSERT INTO  PresenterPresentation VALUES	('	Tired of the CRUD? Automate it!',	'Jack Corbett',2,626);
	INSERT INTO  PresenterPresentation VALUES	('	Top 5 Ways to Improve Your triggers',	'Aaron Bertrand',2,626);
	INSERT INTO  PresenterPresentation VALUES	('	Tricks that have saved my bacon',	'Greg Moore',1,626);
	INSERT INTO  PresenterPresentation VALUES	('	T-SQL : Bad Habits & Best Practices',	'Aaron Bertrand',1,626);
	INSERT INTO  PresenterPresentation VALUES	('	T-SQL for Application Developers - Attendees chose',	'Kevin Goff',2,626);
	INSERT INTO  PresenterPresentation VALUES	('	Tune Queries By Fixing Bad Parameter Sniffing',	'Grant Fritchey',2,626);
	INSERT INTO  PresenterPresentation VALUES	('	Using Extended Events in SQL Server',	'Jason Brimhall',3,626);
	INSERT INTO  PresenterPresentation VALUES	('	Watch Brent Tune Queries',	'Brent Ozar',2,626);
	INSERT INTO  PresenterPresentation VALUES	('	What every SQL Server DBA needs to know about Windows Server 10 Technical Preview',	'David Bermingham',2,626);
	INSERT INTO  PresenterPresentation VALUES	('	What exactly is big data and why should I care?',	'James Serra',1,626);
	INSERT INTO  PresenterPresentation VALUES	('	What is it like to work for Microsoft?',	'James Serra',1,626);
	INSERT INTO  PresenterPresentation VALUES	('	What’s new in SQL Server Integration Services 2012',	'Kevin Goff',2,626);
	INSERT INTO  PresenterPresentation VALUES	('	Why do we shun using tools for DBA job?',	'Paresh Motiwala',2,626);
	INSERT INTO  PresenterPresentation VALUES	('	Why OLAP? Building SSAS cubes and benefits of OLAP',	'Kevin Goff',2,626);
	INSERT INTO  PresenterPresentation VALUES	('	You are Doing It Wrong!!',	'Mike Walsh',2,626);
	END TRY
    BEGIN CATCH
    END CATCH
  END
  GO

  EXEC insertPresenterPresentation
  GO